version: '3'

volumes:
  db:
  static:

services:

  backend:
    build: ./src/
    volumes: 
      - db:/app/db/
      - static:/backend_static/

  gateway:
    build: ./gateway/
    volumes:
      - static:/staticfiles/
    ports:
      - 8000:80
    depends_on:
      - backend
    restart: always
      